CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_users_role CHECK (role IN ('SERVICE_STAFF', 'KITCHEN_STAFF', 'SUPERVISOR', 'MANAGER'))
);

CREATE TABLE user_profiles (
    user_id BIGINT PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    email VARCHAR(254),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id)
        REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    unit VARCHAR(24) NOT NULL,
    quantity DECIMAL(12, 3) NOT NULL DEFAULT 0,
    low_stock_threshold DECIMAL(12, 3) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_stock_quantity_nonnegative CHECK (quantity >= 0),
    CONSTRAINT chk_stock_threshold_nonnegative CHECK (low_stock_threshold >= 0)
);

CREATE TABLE stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    quantity_delta DECIMAL(12, 3) NOT NULL,
    balance_after DECIMAL(12, 3) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    actor_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_transaction_item FOREIGN KEY (stock_item_id)
        REFERENCES stock_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_transaction_actor FOREIGN KEY (actor_user_id)
        REFERENCES app_users(id) ON DELETE SET NULL,
    CONSTRAINT chk_stock_transaction_type CHECK (transaction_type IN ('IN', 'ADJUSTMENT')),
    CONSTRAINT chk_stock_transaction_delta CHECK (quantity_delta <> 0),
    CONSTRAINT chk_stock_transaction_balance CHECK (balance_after >= 0)
);

CREATE INDEX idx_stock_transactions_item_created
    ON stock_transactions(stock_item_id, created_at DESC);
CREATE INDEX idx_app_users_role ON app_users(role);