CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,

    CONSTRAINT fk_payments_session
        FOREIGN KEY (session_id)
        REFERENCES dining_sessions(id) ON DELETE RESTRICT,

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('CASH', 'QR', 'CARD')),

    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED')),

    CONSTRAINT chk_payments_paid_at
        CHECK (
            (payment_status = 'PAID' AND paid_at IS NOT NULL)
            OR
            (payment_status IN ('PENDING', 'FAILED') AND paid_at IS NULL)
        )
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY payments_backend_access ON public.payments
    FOR ALL TO postgres
    USING (true) WITH CHECK (true);

REVOKE ALL ON TABLE public.payments FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.payments_id_seq FROM PUBLIC;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE public.payments FROM anon;
        REVOKE ALL ON SEQUENCE public.payments_id_seq FROM anon;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE public.payments FROM authenticated;
        REVOKE ALL ON SEQUENCE public.payments_id_seq FROM authenticated;
    END IF;
END
$$;