CREATE TABLE dining_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    soup_id BIGINT NOT NULL,
    adult_count INT NOT NULL CHECK (adult_count >= 0),
    child_count INT NOT NULL DEFAULT 0 CHECK (child_count >= 0),
    session_token VARCHAR(100) NOT NULL UNIQUE,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_dining_sessions_table FOREIGN KEY (table_id)
        REFERENCES restaurant_tables(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dining_sessions_package FOREIGN KEY (package_id)
        REFERENCES buffet_packages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dining_sessions_soup FOREIGN KEY (soup_id)
        REFERENCES soups(id) ON DELETE RESTRICT
);

CREATE INDEX idx_dining_sessions_status ON dining_sessions(status);
