CREATE TABLE dining_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    soup_id BIGINT NOT NULL,
    adult_count INT NOT NULL CHECK (adult_count >= 0),
    child_count INT NOT NULL DEFAULT 0 CHECK (child_count >= 0),
    session_token VARCHAR(100) NOT NULL UNIQUE,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT chk_dining_sessions_guest_count CHECK (adult_count + child_count >= 1),
    CONSTRAINT fk_dining_sessions_table FOREIGN KEY (table_id)
        REFERENCES restaurant_tables(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dining_sessions_package FOREIGN KEY (package_id)
        REFERENCES buffet_packages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dining_sessions_soup FOREIGN KEY (soup_id)
        REFERENCES soups(id) ON DELETE RESTRICT
);

CREATE INDEX idx_dining_sessions_status ON dining_sessions(status);
CREATE INDEX idx_dining_sessions_table ON dining_sessions(table_id);
CREATE INDEX idx_dining_sessions_package ON dining_sessions(package_id);
CREATE INDEX idx_dining_sessions_soup ON dining_sessions(soup_id);

CREATE TABLE customer_session_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_customer_grants_session FOREIGN KEY (session_id)
        REFERENCES dining_sessions(id) ON DELETE CASCADE
);
CREATE INDEX idx_customer_grants_session ON customer_session_grants(session_id);
