CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,

    CONSTRAINT fk_payments_session
        FOREIGN KEY (session_id)
        REFERENCES dining_sessions(id) ON DELETE RESTRICT,

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('CASH', 'QR', 'CARD')),

    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED')),

    CONSTRAINT chk_payments_paid_at
        CHECK (
            (payment_status = 'PAID' AND paid_at IS NOT NULL)
            OR
            (payment_status IN ('PENDING', 'FAILED') AND paid_at IS NULL)
        )
);