// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { apiClient } from '../../api/client'
import MasterDataPage from './MasterDataPage'
afterEach(() => { cleanup(); vi.restoreAllMocks() })
it('creates zero-balance stock metadata without sending a quantity', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [] })
  const post = vi.spyOn(apiClient, 'post').mockResolvedValue({ data: { id: 1 } })
  render(<MasterDataPage kind="stock" />)
  await screen.findByText('ยังไม่มีรายการ')
  for(const [label, value] of [['รหัสสต็อก','S01'],['ชื่อรายการ','เนื้อ'],['หน่วย','kg'],['ยอดแจ้งเตือนต่ำ','2.5'],['ยอดเป้าหมายก่อนเปิดร้าน','10']]) fireEvent.change(screen.getByLabelText(label), { target: { value } })
  fireEvent.click(screen.getByRole('button', { name: 'บันทึก' }))
    await waitFor(() => expect(post).toHaveBeenCalledWith('/stock/items', { sku: 'S01', name: 'เนื้อ', unit: 'kg', lowStockThreshold: 2.5, openingTargetStock: 10 }))
  expect(screen.queryByLabelText('ยอดคงเหลือ')).toBeNull()
})
it('lets the manager deactivate a stock item through the stock active endpoint', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [{ id: 7, sku: 'S07', name: 'หมู', unit: 'kg', quantity: 1, lowStockThreshold: 1, openingTargetStock: 5, shortfall: 4, active: true }] })
  const put = vi.spyOn(apiClient, 'put').mockResolvedValue({ data: {} })
  render(<MasterDataPage kind="stock" />)
  await screen.findByText('หมู')
  fireEvent.click(screen.getByRole('button', { name: 'ปิดใช้งาน' }))
  fireEvent.click(screen.getByRole('button', { name: 'ยืนยัน' }))
  await waitFor(() => expect(put).toHaveBeenCalledWith('/stock/items/7/active', { active: false }))
})
it('sends package prices as JSON numbers', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [] })
  const post = vi.spyOn(apiClient, 'post').mockResolvedValue({ data: { id: 1 } })
  render(<MasterDataPage kind="buffet-packages" />)
  await screen.findByText('ยังไม่มีรายการ')
  fireEvent.change(screen.getByLabelText('ชื่อรายการ'), { target: { value: 'Standard' } })
  fireEvent.change(screen.getByLabelText('ราคา'), { target: { value: '299.50' } })
  fireEvent.click(screen.getByRole('button', { name: 'บันทึก' }))
  await waitFor(() => expect(post).toHaveBeenCalledWith('/buffet-packages', {
    name: 'Standard',
    price: 299.5,
    description: '',
  }))
})
it('requires confirmation to reactivate a package and prevents duplicate actions', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [{ id: 1, name: 'Standard', price: 299, active: false }] })
  let resolve!: (v: unknown) => void
  const patch = vi.spyOn(apiClient, 'patch').mockReturnValue(new Promise(done => { resolve = done }))
  render(<MasterDataPage kind="buffet-packages" />)
  await screen.findByText('Standard')
  fireEvent.click(screen.getByRole('button', { name: 'เปิดใช้งาน' }))
  expect(patch).not.toHaveBeenCalled()
  const confirm=screen.getByRole('button', { name: 'ยืนยัน' })
  fireEvent.click(confirm); fireEvent.click(confirm)
  expect(patch).toHaveBeenCalledTimes(1)
  expect(patch).toHaveBeenCalledWith('/buffet-packages/1/active', { active: true })
  resolve({ data: {} }); await screen.findByText('อัปเดตข้อมูลแล้ว')
})
it('displays a server rejection without removing the row', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [{ id: 1, tableNumber: 'T01', capacity: 4, status: 'AVAILABLE' }] })
  vi.spyOn(apiClient, 'delete').mockRejectedValue({ response: { data: { message: 'โต๊ะมีประวัติรอบกิน' } } })
  render(<MasterDataPage kind="tables" />); await screen.findByText('T01')
  fireEvent.click(screen.getByRole('button', { name: 'ลบโต๊ะ' })); fireEvent.click(screen.getByRole('button', { name: 'ยืนยัน' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'โต๊ะมีประวัติรอบกิน')
})

it('removes a package only after confirmation and prevents duplicate delete requests', async () => {
  const get = vi.spyOn(apiClient, 'get').mockResolvedValueOnce({ data: [{ id: 7, name: 'Standard', price: 299, active: true, archived: false }] }).mockResolvedValue({ data: [] })
  let finish!: (value: unknown) => void
  const remove = vi.spyOn(apiClient, 'delete').mockReturnValue(new Promise(resolve => { finish = resolve }))
  render(<MasterDataPage kind="buffet-packages" />)
  await screen.findByText('Standard')
  fireEvent.click(screen.getByRole('button', { name: 'ลบรายการ' }))
  expect(remove).not.toHaveBeenCalled()
  const confirm = screen.getByRole('button', { name: 'ยืนยัน' })
  fireEvent.click(confirm); fireEvent.click(confirm)
  expect(remove).toHaveBeenCalledTimes(1)
  expect(remove).toHaveBeenCalledWith('/buffet-packages/7')
  finish({ data: {} })
  await screen.findByText('นำรายการออกจากรายการใช้งานแล้ว หากมีประวัติยังคงอยู่ในรายการเก็บออก')
  await waitFor(() => expect(screen.queryByText('Standard')).toBeNull())
  expect(get).toHaveBeenLastCalledWith('/buffet-packages')
})

it('keeps the stock item endpoint and excludes removal/archive controls', async () => {
  const get = vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [] })
  render(<MasterDataPage kind="stock" />)
  await screen.findByText('ยังไม่มีรายการ')
  expect(get).toHaveBeenCalledWith('/stock/items')
  expect(screen.queryByRole('button', { name: 'รายการเก็บออก' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'ลบรายการ' })).toBeNull()
})

it('resets archive view and the form when navigation changes master-data kind', async () => {
  const get = vi.spyOn(apiClient, 'get').mockResolvedValue({ data: [] })
  const { rerender } = render(<MasterDataPage kind="soups" />)
  await screen.findByText('ยังไม่มีรายการ')
  fireEvent.click(screen.getByRole('button', { name: 'รายการเก็บออก' }))
  await waitFor(() => expect(get).toHaveBeenLastCalledWith('/soups/archived'))
  expect(screen.queryByRole('button', { name: 'บันทึก' })).toBeNull()
  rerender(<MasterDataPage kind="stock" />)
  await screen.findByText('ยังไม่มีรายการ')
  expect(get).toHaveBeenLastCalledWith('/stock/items')
  expect(screen.getByRole('button', { name: 'บันทึก' })).toBeDefined()
  expect(screen.getByLabelText('รหัสสต็อก')).toHaveProperty('value', '')
})

it('loads the archived list and restores an inactive soup after confirmation', async () => {
  const get = vi.spyOn(apiClient, 'get').mockResolvedValueOnce({ data: [] })
    .mockResolvedValueOnce({ data: [{ id: 9, name: 'Tom Yum', active: false, archived: true }] })
    .mockResolvedValue({ data: [] })
  const restore = vi.spyOn(apiClient, 'post').mockResolvedValue({ data: { id: 9, active: false, archived: false } })
  render(<MasterDataPage kind="soups" />)
  await screen.findByText('ยังไม่มีรายการ')
  fireEvent.click(screen.getByRole('button', { name: 'รายการเก็บออก' }))
  await screen.findByText('Tom Yum')
  expect(get).toHaveBeenLastCalledWith('/soups/archived')
  expect(screen.queryByRole('button', { name: 'บันทึก' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'เปิดใช้งาน' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'คืนรายการ' }))
  expect(restore).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'ยืนยัน' }))
  await waitFor(() => expect(restore).toHaveBeenCalledWith('/soups/9/restore'))
  await screen.findByText('คืนรายการแล้ว กรุณาเปิดใช้งานเมื่อต้องการใช้')
  expect(screen.queryByText('Tom Yum')).toBeNull()
})

it('reports archived-list loading errors and disables removal for occupied tables', async () => {
  vi.spyOn(apiClient, 'get').mockResolvedValueOnce({ data: [{ id: 1, tableNumber: 'A01', capacity: 4, status: 'OCCUPIED' }] })
    .mockRejectedValueOnce({ response: { data: { message: 'โหลดรายการเก็บออกไม่ได้' } } })
  const remove = vi.spyOn(apiClient, 'delete')
  render(<MasterDataPage kind="tables" />)
  await screen.findByText('A01')
  expect(screen.getByRole('button', { name: 'ลบโต๊ะ' }).hasAttribute('disabled')).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'ลบโต๊ะ' }))
  expect(remove).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'รายการเก็บออก' }))
  expect((await screen.findByRole('alert')).textContent).toBe('โหลดรายการเก็บออกไม่ได้')
  expect(screen.queryByText('A01')).toBeNull()
})
